### ISSUE TITLE
Unclear parameters

### ISSUE THREAD

**Issue by artiparty** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#17]
1. What  "isResidencePermitPresent" means? If the current permit is still valid?
2.     familyStatus: "2", —  some elaboration would be helpful, if I'm single without kids, is it 0 or 1 or null? In the form it has no or yes without numbers (screenshot attached)
<img width="505" alt="image" src="https://user-images.githubusercontent.com/6714920/229465424-309fb8d6-fff8-4152-b2f0-67dc8e67ef8c.png">

**Comment by yilmaznaslan** [comment]
Hey, yeah you are right about the missing docu about it, I didn't have time to add them. But briefly, the values are simply the form values
![image](https://user-images.githubusercontent.com/58464107/229472962-1cfc563a-5911-4ae6-8f00-5a5cf62e45c8.png)

1. It stands for whether you have a residence permit already or not. Any better naming suggestion is welcome
2. 2 -> single, 1 -> married or with child
