### ISSUE TITLE
Selenium does not open browser

### ISSUE THREAD

**Issue by alanbui99** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#21]
<img width="1134" alt="Screenshot 2023-04-05 at 23 38 08" src="https://user-images.githubusercontent.com/57241051/230218116-0776a15d-edf2-4db1-8df8-d62d70fbc61a.png">

Hi, I got stuck at this. Selenium never opens the browser for me. Would appreciate some pointer. Thanks

**Comment by yilmaznaslan** [comment]
Looks like selenium is not running. Can you confirm if the selenium server is running ? `docker ps `

**Comment by alanbui99** [comment]
Does this look good?

![338382510_157048826984804_486438397091663930_n](https://user-images.githubusercontent.com/57241051/230462748-f5d8be4f-1f2f-4f33-9883-77789727815d.png)

**Comment by yilmaznaslan** [comment]
Try to restart the docker and then run the application

**Comment by atakanfilgoz** [comment]
> Does this look good?
> 
> ![338382510_157048826984804_486438397091663930_n](https://user-images.githubusercontent.com/57241051/230462748-f5d8be4f-1f2f-4f33-9883-77789727815d.png)

If you use M1 chip, you can try:
`docker run -d -p 4444:4444 seleniarm/standalone-chromium`

**Comment by yilmaznaslan** [comment]
Hi @alanbui99 

The issue is happening when you call `./gradlew run` multiple times in a short time.
In the default selenium config it only allows to have one session and as I know the timeout to delete an session is 5 minutes. 

Solution;

1) Delete the selenium docker `docker stop <ContainerId> && docker rm <ContainerId>`
2) Pull the latest from master and run the selenium host as in the new command in README.md
```shell 
docker run \
  -d \
  --name selenium \
  --net termin \
  -p 4444:4444 -p 7900:7900\
  --shm-size="2g" \
  -e SE_NODE_MAX_SESSIONS=5 \
  -e SE_NODE_OVERRIDE_MAX_SESSIONS=true \
  -e SE_NODE_SESSION_TIMEOUT=120 \
  -t selenium/standalone-chrome:latest
```

**Comment by alexeyshulzhenko** [comment]
@yilmaznaslan  I had the issue with the line  `--net termin \ `on mac.
Then some Java issues and in the end managed to fix everything with `docker run -d -p 4444:4444 seleniarm/standalone-chromium`

At least is seems to be working fine now (not sure if it should stay on 75%
<img width="865" alt="Screenshot 2023-04-11 at 18 32 30" src="https://user-images.githubusercontent.com/11439023/231229141-c375ab5d-8dff-41f3-9b26-0f510573c0f9.png">

**Comment by yilmaznaslan** [comment]
Oh yeah. The --net flag is not necessary. I have removed it from readme, thanks
