### ISSUE TITLE
Personal info form for singles

### ISSUE THREAD

**Issue by atakanfilgoz** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#22]
It is not an issue but a question. For people who are single, is changing "isThereFamilyMember" field to "no" in DEFAULT_PERSONAL_INFO_FORM.json file sufficient? Or do they need to change anything else? If it is okay, maybe we can put this json file as an example.

```
{
  "citizenshipValue": "Turkey",
  "citizenshipValueOfFamilyMember": "Turkey",
  "numberOfApplicants": "one person",
  "isThereFamilyMember": "no",
  "firstName": "name",
  "lastName": "surname",
  "emailAddress": "abc@gmail.com",
  "birthdate": "DD.MM.YYYY"
}
```

Thanks in advance!

**Comment by yilmaznaslan** [comment]
Thanks for finding it. I have created another json for it
