### ISSUE TITLE
App failing when running on "Starting to selectCitizenshipValue"

### ISSUE THREAD

**Issue by alexeyshulzhenko** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#27]
Hello, thank you for an amazing tool! It worked perfectly yesterday, but today I started to get these errors:

<img width="1000" alt="Screenshot 2023-04-12 at 10 50 02" src="https://user-images.githubusercontent.com/11439023/231405272-6910ccff-c827-46ad-bc3f-32e839ade4ed.png">

The browser starts normally, the app opens the LEA page, goes through the first step, and fails on the CitizenshipValue. I assume that form loads too slowly. Are there any workarounds how to fix that?

**Comment by yilmaznaslan** [comment]
Yeah I check from the main web page it is very slow. I have increased the timeout for page loading to 60 seconds and made it parameterized. Pull from master and run as usual. If that is not enough, you can also increase it from https://github.com/yilmaznaslan/berlin-auslaenderbehorde-termin-bot/blob/f32d4df2061f19b07e4ee83a961f72816d03b0a4/src/main/resources/config.properties#L2 and run the application
