### ISSUE TITLE
Program gets suck after coming to the "Apply for a residence title" step

### ISSUE THREAD

**Issue by onatatmaca** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#32]
Hey again,
The bot was working perfectly, but I'm not sure when (probably after the updated files) it stopped working for me, where the program stops working after filling the first three spaces, and it is unable to select the "Apply for a residence title" option. 
<img width="1005" alt="Screenshot 2023-04-24 at 01 36 38" src="https://user-images.githubusercontent.com/76392684/233872549-185d0d22-331e-4e0a-966b-1f3d6f209702.png">

I've tried it on my Mac and my PC, however both had the same issue. Do you maybe have an idea for a solution? Thanks!

**Comment by onatatmaca** [comment]
<img width="679" alt="Screenshot 2023-04-24 at 01 41 19" src="https://user-images.githubusercontent.com/76392684/233872631-872679c0-c3d5-460a-8f54-558a552c48fd.png">

Here's my text file where the option is written :)

**Comment by yilmaznaslan** [comment]
If you have a family member, you need to use this one https://github.com/yilmaznaslan/berlin-auslaenderbehorde-termin-bot/blob/cd51d03ad6acd75f0158d351a7138921a4364f8a/src/main/resources/DEFAULT_PERSONAL_INFO_FORM_WITH_FAMILY.json

It works, closing the issue
