### ISSUE TITLE
Page refresh on form submit?

### ISSUE THREAD

**Issue by lakshkhanter** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#35]
Hi, I've just deployed the script and it seems to be going through all the steps just fine. I had a question around next steps:

1. Is the script submitting the form? The page seems to go back to the home screen, I'm unable to see the page with the "No appointments available" red banner on the top.
2. If the form is successful and slots are available, is there any manual input required at that point to book the appointment? Or does the script pick the first available slot automatically and confirm the appointment?

Thanks a lot for this script, it's made the process incredibly easy! 

https://user-images.githubusercontent.com/18573813/234292876-6db85204-6a35-4b1c-b4f8-184fa2296c39.mp4

**Comment by yilmaznaslan** [comment]
Hi 

- It just happens very fast that you don't see the form being submitted. I would make it a stop once the red banner comes but it would just slow the process. But yeah maybe it is better to stop for 1-2 seconds after being submit. I will improve the logs so you can follow from the logs better
- Yes it automatically picks the first available slot and books

**Comment by lakshkhanter** [comment]
Amazing, thanks for your quick response!
