### ISSUE TITLE
Service selection not always sends the data

### ISSUE THREAD

**Issue by piratejet** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#37]
sometimes when the internet connection is slow or some selection tasks take a bit longer it doesn't send the data, reloads the page and starts from the beginning.

P.S. thanks for the great tool

**Comment by yilmaznaslan** [comment]
Yes, so what is the issue here ?

**Comment by piratejet** [comment]
you will see that it doesnt submit the form and there is no response or something that tells you that there is no available dates, and then it starts again, so probably the next button to submit the form doesnt work

**Comment by yilmaznaslan** [comment]
It does, it just happens so fast that you don't see it. There was another person asking for the same thing, I will wait 1-2 seconds after the form submission

**Comment by piratejet** [comment]
i suspect that it does not because there should be a second loader animation for the submit. the one loader that we see in the selection form is when it clicks the visa type. and then there should be another loader. Also i dont see any error message that there are no available dates. and the page is just open without sending an actual submit request. it should be like this https://streamable.com/une029

but in some cases when the visa type response is fast. it works just fine

**Comment by piratejet** [comment]
sometimes it refreshs even earlier, you can see here. i am also pressing Next button manually to show how the flow should be https://streamable.com/9w26ey

**Comment by yilmaznaslan** [comment]
Pushed a fix. Pull from master and try again, it should now work better for such cases

**Comment by nekoemperor** [comment]
Hi, It's really good stuff that you built here btw. 
I just wanna ask if it's possible or worth it to change the flow of the bot so that it doesn't run from the beginning or homepage every time the error message is showing after form submission?

So, basically after we get the error message, the bot will click the button 'Next' again instead of running from the homepage, and then after few attempts the bot can 'reset' and run from the homepage again.

Once again, really appreciate what you've been doing :))

**Comment by yilmaznaslan** [comment]
yeah I think that makes sense. I will look at it. As long as there is a. remaining time for the session, the reload can be skipped

**Comment by nekoemperor** [comment]
and other issue that I have been experiencing is that sometimes one of the fields is not selected.

![test](https://user-images.githubusercontent.com/64539393/235088450-3d44ab4d-d319-461f-970e-99e6a314fb5b.jpg)

**Comment by Avens8** [comment]
Hi! Thanks man for amazing work :)

Btw, I found out some issues with selecting available dates last night. The bot couldn't choose a day for some reason.

![exception_2023-05-03_22:46:20_exception](https://user-images.githubusercontent.com/21984491/236137927-c110e238-f0c9-4b9a-8756-6a7116de0ba3.png)

[exception_2023-05-03_22:46:20_exception.html.zip](https://github.com/yilmaznaslan/berlin-auslaenderbehorde-termin-bot/files/11394729/exception_2023-05-03_22.46.20_exception.html.zip)

**Comment by Avens8** [comment]
And here is the bot logs:
```shell
2023-05-04 08:22:08 ERROR TerminFinder Exception occurred during the process, quitting.
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for org.example.formhandlers.Section2ServiceSelectionHandler$$Lambda$459/0x00000008403e5840@72b6537c (tried for 60 second(s) with 500 milliseconds interval)
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.0-21-cloud-amd64', java.version: '11.0.18'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 112.0.5615.165, chrome: {chromedriverVersion: 112.0.5615.49 (bd2a7bcb881c..., userDataDir: /tmp/.com.google.Chrome.W2F5vh}, goog:chromeOptions: {debuggerAddress: localhost:40075}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.17.0.2:4444/sessio..., se:cdpVersion: 112.0.5615.165, se:vnc: ws://172.17.0.2:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.17.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: a24d38c470e44f234c33d54f48273b8a
        at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:87) ~[selenium-support-4.8.1.jar:?]
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231) ~[selenium-support-4.8.1.jar:?]
        at org.example.formhandlers.Section2ServiceSelectionHandler.sendForm(Section2ServiceSelectionHandler.java:237) ~[main/:?]
        at org.example.formhandlers.Section2ServiceSelectionHandler.fillAndSendForm(Section2ServiceSelectionHandler.java:74) ~[main/:?]
        at org.example.TerminFinder.fillAndSendFormWithExceptionHandling(TerminFinder.java:115) ~[main/:?]
        at org.example.TerminFinder.run(TerminFinder.java:85) ~[main/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by yilmaznaslan** [comment]
Do you have the full logs of that ? Unfortunately I can't find out the reason only from this output

**Comment by yilmaznaslan** [comment]
I pushed a fix . Please pull from master and try again
