### ISSUE TITLE
Could not compile settings file

### ISSUE THREAD

**Issue by afzal-hossain-ovi** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#38]
Hi, I am facing this problem when I try to run gradlew.

java --version
java 20.0.1 2023-04-18

<img width="814" alt="Screenshot 2023-04-28 at 1 24 22 PM" src="https://user-images.githubusercontent.com/25689142/235135299-39f3db0e-1008-482e-ae78-baf6487542c4.png">

**Comment by nekoemperor** [comment]
From my experience, I had to downgrade Java JDK to version 17. That should fix the problem.

**Comment by afzal-hossain-ovi** [comment]
> From my experience, I had to downgrade Java JDK to version 17. That should fix the problem.

/
/
