### ISSUE TITLE
Send notification sound

### ISSUE THREAD

**Issue by neeteshp** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#42]
Can we add notification sound, when calendar page is opened? In case, if there are any errors in selecting or filling the data, we can do it manually.

**Comment by seraphczx** [comment]
I tried filling it manually, but the webpage always broke during this stage, I guess you have to terminate the docker first to make it possible for you to fill the data manually.

**Comment by yilmaznaslan** [comment]
I am building this tool to automate the whole process from the beginning to the end. Thus I am not planning to implement an alarm or notifier.
