### ISSUE TITLE
is not clicking on "apply for residency title" for "two word" countries.

### ISSUE THREAD

**Issue by Xenon112** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#48]
sounds funny but is true.

I tried everything until i realized that is not clicking because of the country for family member selection. I try single word countries it works flawlessly. 

![issue1](https://github.com/yilmaznaslan/berlin-auslaenderbehorde-termin-bot/assets/79414082/2dfc7fa2-7b88-437d-a94f-2e283cf408c0)
![issue2](https://github.com/yilmaznaslan/berlin-auslaenderbehorde-termin-bot/assets/79414082/765f0d96-ac65-4542-a35d-614b0fbf58c1)
![issue3](https://github.com/yilmaznaslan/berlin-auslaenderbehorde-termin-bot/assets/79414082/0e6016c5-d5af-4d6f-849a-a41c5331ccc1)

do you have any idea how to fix? 

Thank you. And great work!

**Comment by yilmaznaslan** [comment]
Can you send the log outputs as well as the json files you used. There light be a typo in the json maybe

**Comment by Xenon112** [comment]
both json where copied from the other forms just changed the values


DEFAULT_PERSONAL_INFO_FORM.json
{
  "citizenshipValue": "Albania",
  "citizenshipValueOfFamilyMember": "Russian Federation",
  "numberOfApplicants": "two people",
  "isThereFamilyMember": "yes",
  "firstName": "Xheni",
  "lastName": "Hoxha",
  "emailAddress": "nwoxenon@gmail.com",
  "birthdate": "12.01.1993"
}

DEFAULT_VISA_APPLICATION_FORM.json
{
  "isResidencePermitPresent": false,
  "residencePermitId": null,
  "serviceType": "Apply for a residence title",
  "visaPurposeValue": "Economic activity",
  "visaLabelValue": "EU Blue Card / Blaue Karte EU (sect. 18b para. 2)"
}
![log](https://github.com/yilmaznaslan/berlin-auslaenderbehorde-termin-bot/assets/79414082/a0479a53-cb1b-48bd-a90b-71da8caa9e6a)

**Comment by yilmaznaslan** [comment]
pushed a fix. Please pull from master and run again

**Comment by Xenon112** [comment]
is fixed closing the issue thanks!
