### ISSUE TITLE
Send Form is broken with website update

### ISSUE THREAD

**Issue by Panger95** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#50]
The way the sendForm() is processed is broken after the latest website update and seems to be throwing a lot of errors now. The website doesn't ask for a next click anymore and automatically tells you if an appointment is available or not anymore after selecting which type you need. Attempting to click the next button on the page now breaks the script and throws and error if the button is not clickable.

**Comment by onatatmaca** [comment]
Yes, the script currently doesn't work unfortunately. :(

**Comment by allentiak** [comment]
@yilmaznaslan
Shall we either rename this or closing it in favor of #83?
