### ISSUE TITLE
No action in calendar page

### ISSUE THREAD

**Issue by Sh-Nael** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#58]
Hi,
I downloaded the codes and have run it today but facing below errors when it reaches the calendar page (with slots available) and it starts over from the beginning:

2023-07-19 16:26:43 INFO TerminFinder page is saved
2023-07-19 16:26:43 INFO DriverUtils Initializing the driver. Host: localhost, try: 0
Jul 19, 2023 4:26:43 PM org.openqa.selenium.remote.RemoteWebDriver checkNonW3CCapabilities
**WARNING:** Support for Legacy Capabilities is deprecated; You are sending the following invalid capabilities: [unexpectedAlertBehaviour]; Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/
Jul 19, 2023 4:26:43 PM org.openqa.selenium.remote.ProtocolHandshake createSession
**WARNING:** Support for Legacy Capabilities is deprecated; You are sending the following invalid capabilities: [unexpectedAlertBehaviour]; Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/
2023-07-19 16:26:43 INFO DriverUtils Driver is initialized.
2023-07-19 16:26:48 INFO TerminFinder Starting to getHomePage
2023-07-19 16:26:48 INFO TerminFinder Getting the URL: https://otv.verwalt-berlin.de/ams/TerminBuchen?lang=en

**Comment by allentiak** [comment]
@Sh-Nael Thanks for your comment.
Feel free to add more information in #83.

@yilmaznaslan
Shall we close this one?
