### ISSUE TITLE
The problem of the path of JAVA_HOME

### ISSUE THREAD

**Issue by ChangMUINSA** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#60]
Hello,

When i follow your steps of this application, i have met a problem like this:

The JAVA_HOME environment variable is configured with an incorrect path to my Java installation. 

![image](https://github.com/yilmaznaslan/berlin-auslaenderbehorde-termin-bot/assets/114908421/08a7561d-5d99-413b-8575-2af2514276a3)

Can you give me some suggestions to solve it ?  Thank you very much. :)

**Comment by allentiak** [comment]
Have you checked the Java version?
It should be >= 17.
