### ISSUE TITLE
Problems with "citizenshipValueOfFamilyMember" and missing the 'Special rights of residence' section

### ISSUE THREAD

**Issue by korkny** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#61]
Hey there, once again my gf and I are trying to get another appointment, this time for a visa for "Residence card for family members of EU (except Germany) and EEA citizens". 

I've encountered a couple of problems. 

1. The bot seems to get me no further than 'Starting to selectCitizenshipValueOfFamilyMember' and goes no further. I have made sure that "Ireland" is spelled correctly and matches the website but it doesn't seem to select it. 

2. I don't see any folder or anything in the code that corresponds with the specific type of visa I need - it's listed in a subsection at the bottom of the page called 'Special rights of residence' -  separate from the 'family reasons' drop down. So I'm concerned that even if the right family member citizenship value is selected, it won't select the correct visa. 

I know that the site is super glitchy, and I've noticed it's even more messed up in English. When I go through the website in german, as soon as i click 'ireland', i click 'apply for a residence title' and automatically  there is only one option that appears: "Residence card for family members of EU (except Germany) and EEA citizens" (in German of course)

However when I go through it in English, once I select 'Ireland' a trillion duplicate buttons come up, and even if I press one of the 'apply for a residence title' buttons, I have to manually scroll and select the 'special rights of residence' section and the correct option within those options. 

All this to say - the website is acting up and I wonder if there's any way to get around this weird glitch?

Any help or work arounds would be appreciated!

Thanks for all your hard work, 
Courtney

**Comment by yilmaznaslan** [comment]
In the english site I don't see the irland. Thats why bot is failing to select citizenship.

<img width="377" alt="image" src="https://github.com/yilmaznaslan/berlin-auslaenderbehorde-termin-bot/assets/58464107/98c2b517-7e2e-4d36-b038-eb4510c359ab">

**Comment by allentiak** [comment]
@korkny 

Thanks for reaching out.

w.r.t. 1, it seems to be a website problem. Not much to do about it from this end. I suggest you complain directly to the Foreigners Office...

w.r.t. 2, feel free to try the procedure manually once, and then sharing the resulting .json. in a PR.
That's what I did in #66, for the job-seeker visa...

@yilmaznaslan 
Shall we close this one?
