### ISSUE TITLE
Error during booking process

### ISSUE THREAD

**Issue by ask5301** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#7]
Hi there! First of all Thank you for the so great and useful tool. 

I got following error during booking process all the time:
It opens first page and crashes after clicking on **Book Appointment** as soon as page is starting to load.

> 2023-03-24 11:20:47 INFO Section1MainPageHandler Starting to fill the form
> 2023-03-24 11:20:47 INFO LogUtils Element: Book Appointment, Process:GETTING_BY_ID, Status:SUCCESSFUL
> 2023-03-24 11:20:50 INFO ThreadMonitor Number of threads: 6
> 2023-03-24 11:20:52 INFO LogUtils Element: Book Appointment, Process:CLICKING_TO_ELEMENT, Status:Successful
> 2023-03-24 11:21:20 INFO ThreadMonitor Number of threads: 6
> 2023-03-24 11:21:30 WARN LogUtils Element: checkbox, Process:GETTING_BY_ID, Status:FAILED Msg:
> 2023-03-24 11:21:30 ERROR TerminFinder Error in initializing a new session. Exception: 
> org.example.exceptions.ElementNotFoundTimeoutException: checkbox
>         at org.example.utils.DriverUtils.getElementByTagName(DriverUtils.java:92) ~[main/:?]
>         at org.example.business.formhandlers.Section1MainPageHandler.clickToAcceptConsent(Section1MainPageHandler.java:38) ~[main/:?]
>         at org.example.business.formhandlers.Section1MainPageHandler.fillAndSendForm(Section1MainPageHandler.java:27) ~[main/:?]
>         at org.example.TerminFinder.run(TerminFinder.java:78) [main/:?]
>         at java.util.TimerThread.mainLoop(Timer.java:556) [?:?]
>         at java.util.TimerThread.run(Timer.java:506) [?:?]
> 2023-03-24 11:21:30 ERROR TerminFinder Error in initializing a new session. Exception: 
> org.openqa.selenium.NoSuchSessionException: invalid session id
> Build info: version: '4.8.1', revision: '8ebccac989'
> System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.19.0-38-generic', java.version: '11.0.18'
> Driver info: org.openqa.selenium.remote.RemoteWebDriver
> Command: [d9a8a3fc9b5b6291c4be27198592f6e6, getCurrentWindowHandle {}]
> Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 110.0.5481.177, chrome: {chromedriverVersion: 110.0.5481.77 (65ed616c6e8e..., userDataDir: /tmp/.com.google.Chrome.V5UCrk}, goog:chromeOptions: {debuggerAddress: localhost:43633}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.17.0.2:4444/sessio..., se:cdpVersion: 110.0.5481.177, se:vnc: ws://172.17.0.2:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.17.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
> Session ID: d9a8a3fc9b5b6291c4be27198592f6e6
>         at jdk.internal.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source) ~[?:?]
>         at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
>         at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200) ~[selenium-remote-driver-4.8.1.jar:?]
>         at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133) ~[selenium-remote-driver-4.8.1.jar:?]
>         at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53) ~[selenium-remote-driver-4.8.1.jar:?]
> at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184) ~[selenium-remote-driver-4.8.1.jar:?]
>         at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51) ~[selenium-remote-driver-4.8.1.jar:?]
>         at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543) ~[selenium-remote-driver-4.8.1.jar:?]
>         at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:598) ~[selenium-remote-driver-4.8.1.jar:?]
>         at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602) ~[selenium-remote-driver-4.8.1.jar:?]
>         at org.openqa.selenium.remote.RemoteWebDriver.getWindowHandle(RemoteWebDriver.java:467) ~[selenium-remote-driver-4.8.1.jar:?]
>         at org.example.TerminFinder.getFormPage(TerminFinder.java:150) ~[main/:?]
>         at org.example.TerminFinder.run(TerminFinder.java:62) [main/:?]
>         at java.util.TimerThread.mainLoop(Timer.java:556) [?:?]
>         at java.util.TimerThread.run(Timer.java:506) [?:?]

Could you please check what is wrong

**Comment by ask5301** [comment]
> Hi, the logs you see shouldn't block the execution of the program. Sometimes page doesn't load because of latency of server-side issues. So it results in timeout errors. In the next iterations it generally works, like below

Well Unfortunately all  tries are not successful. All the time i got this error. Even after last update.

**Comment by ask5301** [comment]
I solve my issue by adding flag --shm-size=2g in docker start line - it allows docker to use host memory. Seems like problem was in memory shortage.

**Comment by yilmaznaslan** [comment]
I have misunderstood the problem, I thought it was the issue in the web server. Well have added that to the readme . Thanks for finding
