### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by coskukoz** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#74]
I can't make it run somehow on my Mac. Maybe due to my installations of Java.
Apple M1 Chip

<img width="1188" alt="Screen Shot 2023-10-12 at 21 59 06" src="https://github.com/yilmaznaslan/berlin-auslaenderbehorde-termin-bot/assets/13234742/a3a90a4a-a934-435f-a242-fd8d866d83ec">

Here is my Java versions:
<img width="487" alt="Screen Shot 2023-10-12 at 21 59 17" src="https://github.com/yilmaznaslan/berlin-auslaenderbehorde-termin-bot/assets/13234742/4c202cbd-942e-4e4a-9ab3-ce7575d19051">

**Comment by coskukoz** [comment]
Solved my issue with below code change:

<img width="1005" alt="Screen Shot 2023-10-12 at 22 40 06" src="https://github.com/yilmaznaslan/berlin-auslaenderbehorde-termin-bot/assets/13234742/43ebb72a-5494-44ea-bea5-080ee668be9c">

**Comment by yilmaznaslan** [comment]
Your java version is 11. You need to run it with java 17 if you dont want to change the code

**Comment by allentiak** [comment]
@coskukoz I've just opened #82. Feel free to open a PR for the README!

@yilmaznaslan Shall we close this one?
