### ISSUE TITLE
Hi, was I doing correctly, I am new to Docker, thanks in advance.

### ISSUE THREAD

**Issue by dejavuVision** [yilmaznaslan/berlin-auslaenderbehorde-termin-bot#9]
![selenium](https://user-images.githubusercontent.com/129516990/229121847-52afc3fc-3ae1-499d-870c-0b9c8a35d98b.jpg)
Hi, please take a look at my attached photo. Does it mean that the program is running to find an appointment for me? All I have to do is waiting? 

Thank you and have a good day!

**Comment by yilmaznaslan** [comment]
Hey, I pushed some fixes to master, please pull from the master run the application again using `./gradlew run` in terminal. If there is any issue provide the whole error log please

**Comment by OneCornn** [comment]
Hey, probably I have the same error 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/109863933/229339633-e5a72d46-1dbe-4820-bbd8-a63c938a7f99.png">

**Comment by yilmaznaslan** [comment]
Can you please checkout the latest master and try it out again

**Comment by OneCornn** [comment]
Seems to work, thank you! There was also small issue with Seleniumhub in readme guide, I couldn't run selenium with parameter "--net termin", it runs after removing .

**Comment by dejavuVision** [comment]
Hi, thank you for your updates. I guess it's working now right? 
![image](https://user-images.githubusercontent.com/129516990/229380212-a9e302db-1307-44f4-a75f-fc860cd8e785.png)

**Comment by yilmaznaslan** [comment]
yes looks so
